### ISSUE TITLE
Support for Unix wildcards

### ISSUE THREAD

**Issue by andrei-cacio** [boblauer/mock-require#11]
Is there a way to use unix wildcards?

Something like so: `mock('*.scss');`. I think this would be useful if you want to mock CSS modules for unit testing.

It may be a stupid suggestion, but I thought it was worth sharing it.

**Comment by boblauer** [comment]
I don't plan on supporting wild cards, as I would like to only support inputs that are supported by `require` itself.

That said, mocking every `scss` file in a given folder should be fairly easy using something like `glob`:

```js
glob('**/*.scss', (err, files) => {
  files.forEach(file => mock(file, 'my-mock-file.scss'));
});
```

Would something like that work for what you're trying to accomplish?

**Comment by andrei-cacio** [comment]
Yes, it should do just fine.

Thanks!
