### ISSUE TITLE
reRequire() returns what mock-require exports

### ISSUE THREAD

**Issue by mightyiam** [boblauer/mock-require#12]
So I'm using https://www.npmjs.com/package/decache and `require` instead. That actually works, so, perhaps you can just swap out the implementation with that.

It seems that `getFullPath` returns the path to `mock-require`, instead of to the correct module.

**Comment by boblauer** [comment]
Would you be able to provide sample code that reproduces this bug?

**Comment by mightyiam** [comment]
Here you go: https://github.com/mightyiam/modify-pkg-up/pull/2

**Comment by mightyiam** [comment]
Is it clear how to run the the example branch, @boblauer ?

**Comment by boblauer** [comment]
In your example, what file is `subjectPath` supposed to point to?  I assume `index.js`?

**Comment by mightyiam** [comment]
@boblauer indeed.

**Comment by boblauer** [comment]
Fix published on npm `@2.0.1`.  Thanks for the issue!

**Comment by mightyiam** [comment]
Cool, @boblauer. Thank you.
