### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'module'

### ISSUE THREAD

**Issue by ngocketit** [boblauer/mock-require#13]
I'm using this module with node version 0.12.17 and got the error:

`ModuleNotFoundError: Module not found: Error: Cannot resolve module 'module' in node_modules/mock-require`

Any ideas of what could be wrong?

**Comment by boblauer** [comment]
What do you get when you run `node -p "require('module')"` in your terminal?

**Comment by ngocketit** [comment]
That works. There is nothing wrong with `node` or `module`. The problem is am using this with Webpack and the `target` is by default set to `web`. If I change it to `node` or `node-webkit`, I got another issue, something like `Cannot resolve module 'module-a'` in the test folder of `mock-require`. I've tried several similar modules but neither works.

**Comment by boblauer** [comment]
Yeah, I wouldn't expect this to work in any non-node environment. Sorry I can't be more help.

**Comment by eetievent** [comment]
In Webpack, you can try to avoid importing modules which will be available at runtime:
package.json:
"browser": {
  "module": false
}
I tried this tests with angular/webpack/karma/jasmine, it corrects the error, but then the tests wouldn't start at all (without any error)...
