### ISSUE TITLE
mock-require not always called with Mocha

### ISSUE THREAD

**Issue by vlindhol** [boblauer/mock-require#14]
I'm mocking some libraries using `mock-require` in my unit tests. I'm using Mocha 3.1.2 and Node 4.7.0. I have my tests in the folder `test` in separate files. Running `mocha test/foo.js` works perfectly, but running `npm test` (which in turn runs `mocha --reporter spec test/*.js`) makes the same tests in `test/foo.js` fail! To be exact, the `require` statements sometimes still return the real libraries, not the mocked ones.

I inserted some debugging statements in mock-require, especially in the overridden `Module._load` function, and it seems like that function is not being called for all require statements. For example: if the file `test/foo.js` requires `src/bar.js`(using the correct path of course) and that file requires `src/libAsdf.js`, then the overridden `Module._load` is correctly called when requiring `src/bar.js` but NOT when requiring `src/libAsdf.js`. This is always the pattern: `mock-require` works for the first link in a `require` chain, but not after that.

NOTE: This only happens when running mocha on all my tests. Running individual test files, `mock-require` is correctly used for all files in the dependency tree.

I couldn't spot any obvious answer to this problem, I suppose it's some magic that Mocha does. Any tips?

**Comment by boblauer** [comment]
When you say it works for the first file in the chain but not subsequent, I'm not sure I understand what you mean. If bar.js is mocked correctly, then any files it requires shouldn't be required because the real bar.js isn't ever loaded into memory.

**Comment by boblauer** [comment]
@vlindhol Any update on this?

**Comment by vlindhol** [comment]
I mean that I am mocking `src/libAsdf.js`in my test file `test/foo.js`, which runs tests for the file `src/bar.js`.

So the dependency chain is `test/foo.js` -> `src/bar.js` -> `src/libAsdf.js`. I inserted a `console.log` statement into the new `Module._load` provided by mock-require, to see that it gets called correctly. In the first arrow of the dependency chain, the correct `Module._load` gets called and loads `src/bar.js` from disk, which is correct since it's not mocked. However, in the next arrow on the chain, the original Node version of `Module._load` is called. In other words it loads the `libAsdf.js` file as usual, not knowing anything about the mocked version.

And the thing is that the behaviour is different depending on how I run the mocha tests. If I run only `mocha test/foo.js` I can see from my debugging statement that the correct version of `Module._load` gets called for all files, even deeply nested `require`s. If I run the whole test suite, `Module._load` works once (i.e. for the first arrow in the chain) and then it reverts to the Node version.

**Comment by vlindhol** [comment]
I'll try to get a minimal test case going, and see if I even can reproduce it in another codebase than the one I'm using mock-require for. But I'm quite busy at work at the moment, so it'll be a while!

**Comment by boblauer** [comment]
Closing for now, feel free to re-open in the future.
