### ISSUE TITLE
How to mock requires inside an imported module?

### ISSUE THREAD

**Issue by finferflu** [boblauer/mock-require#16]
Hi,

I'm using Jasmine to test a helper module that contains a few requires. I have tried to use the `reRequire` method, but it does not seem to do the trick:

```javascript
beforeEach(function () {
    mock('mime', { lookup: function () {
      return 'application/sadsda'
    }})

    helper = mock.reRequire('./helper')}
```

When I test a method in the helper module, I can see that the actual modules are being used, rather than the mocks. Am I doing something wrong?

Thank you.

**Comment by boblauer** [comment]
And inside of your test, you're testing `helper` directly?  In other words, you're calling `helper.something()` within the test file, which in turns calls `mime.lookup()`?

**Comment by finferflu** [comment]
Yes, that's correct.

**Comment by finferflu** [comment]
Hang on, I've just caught my own typo there... I wasn't re-requiring the module correctly. Everything works as expected now. Thanks anyway for checking!

**Comment by boblauer** [comment]
Great, glad to hear everything is working.
