### ISSUE TITLE
Mocking a module with constructor

### ISSUE THREAD

**Issue by finferflu** [boblauer/mock-require#17]
Hi,

I'm trying to mock-require the [js-ubersmithclient](https://www.npmjs.com/package/js-ubersmithclient) module, however it uses a constructor, like this:

```javascript
const Ubersmith = require('js-ubersmithclient')
let ubersmithClient = new Ubersmith(url, username, password)
```

And then you can actually use the various functions that the API provides, e.g.:

```javascript
ubersmith.uber.check_login({login: username, pass: password})
.then(...)
```
(where `uber.check_login` is just what the API provides, and not part of the module itself).

Is there any way that `mock-require` can mock that sort of constructor and the subsequent API calls?

Thank you.

**Comment by boblauer** [comment]
You will have to determine ahead of time what methods you need to mock, and then write a class that has those same methods, except that they will be mocks instead of the actual methods.

For example, `mockRequire('js-ubersmithclient', './mock-ubersmithclient')`

```js
// mock-ubersmithclient.js
module.exports = class MockUbersmithclient {
  constructor() {
    this.uber = this;
  }

  check_login() {
    return Promise.resolve();
  }
}
```

**Comment by finferflu** [comment]
Thanks for that, your suggestion makes perfect sense. I hadn't thought about creating an actual mock module in a separate file. Thanks again.

**Comment by boblauer** [comment]
Glad to help!
