### ISSUE TITLE
Ability to mock missing deps.

### ISSUE THREAD

**Issue by kilianc** [boblauer/mock-require#18]
My use case requires me to support two behaviors, one for one a module exists and one if it's, missing. I tried to use this module to write the test suite for both scenarios but this:

```js
mock({
  './hello.json': { foo: 'bar' }
})

require('./hello.json')
```
yields 

```
Error: Cannot find module './hello.json'
  at Function.Module._load (node_modules/mock-require/index.js:24:22)
  at require (internal/module.js:20:19)
  at Context.it.only (index.test.js:32:5)
```

Is this a missing feature or I am missing something?

**Comment by doowb** [comment]
@kilianc I think you're just passing in the parameters to `mock` incorrectly. It should be [`(path, obj)`](https://github.com/boblauer/mock-require#mockpath-mockexport):

```js
var mock = require('mock-require');
mock('./hello.json', {"foo": "bar"});

console.log(require('./hello.json'));
```

**Comment by boblauer** [comment]
Thanks @doowb, and my apologies @kilianc for missing this when you first opened it.
