### ISSUE TITLE
Use normalize() for consistency in Windows

### ISSUE THREAD

**Issue by mscottx88** [boblauer/mock-require#20]
The method getFullPath() does not take into consideration Win32 environments with mixed Posix style require strings.

For instance:

mockRequire(process.cwd() + "/" + path, obj);

In Posix environment the backslash remains, but in Win32 environment, the backslash becomes a forward slash "\".

To overcome, wrap the result of getFullPath() with a call to normalize(), exposed by the path module.

**Comment by tiagomapmarques** [comment]
@mscottx88, was #33 what you had in mind?
