### ISSUE TITLE
travis ci

### ISSUE THREAD

**Issue by thomasmeadows** [boblauer/mock-require#27]
Travis Ci does not seem to work with mock requires the same as what I have locally, is there anything that could cause mock require not to work in their environment?

This probably isn't really an issue with mock require but I figured it would be best to open one in case others run into the same problem

**Comment by boblauer** [comment]
The one thing that immediately comes to mind is ensuring that Travis is running the same version of node that you're running locally.  And ensuring Travis is running the same version of `mock-require` as well.  Do you have your dependencies locked down with either a `yarn.lock`, `shrinkwrap.json`, or `package-lock.json` file?

**Comment by thomasmeadows** [comment]
yeah I checked that already, running the latest version of node 6@6.12.3, and latest mock-require@2.02.   It seems to be something weird with the paths.  I am also using ava for unit testing which has some built in babel abilities.

**Comment by thomasmeadows** [comment]
Sorry, it seems this is unrelated to travis and mockrequire.  There might be a problem with not being able to mock .json files, but i've solved it in my case ftmp
