### ISSUE TITLE
The mocked module is still loaded

### ISSUE THREAD

**Issue by otryshko** [boblauer/mock-require#31]
The module which I'm trying to mock refers to global variables which do no exist in my node environment. I'd like that module to be not loaded at all, but simply mocking it with mock('myModule', {}); still makes it (and its imports as well) to be loaded. Is there a way to just not load that module?

**Comment by boblauer** [comment]
I suspect something else is going on, because it should never load the real module when mocking it:

https://github.com/boblauer/mock-require/blob/master/test/runner.js#L88

Are you using `import` statements via babel by chance?

**Comment by otryshko** [comment]
@boblauer I'm sorry, operator error. That module have been loaded in another place via other means, and mock is working as expected. Thank you for the tool!
