### ISSUE TITLE
Cannot get to work with an express route module

### ISSUE THREAD

**Issue by saiait** [boblauer/mock-require#38]
I am trying to mock a dependency in a route module in an express js server but cannot get it to work.
I tried everything with the route module loaded in the main server/index.js file so I thought ok just remount the route on another root path so to have two paths to the routes with different prefixes like when you version an end point but this one will be for testing with the mocked service/business layer module which is called ecourier.controller in my sample.  See below but even then on the new /apitest route path it still does not mock the Module.... AWWWWWW..

Please what am I doing wrong...

import chai from 'chai';
import server from '..';

var mock = require('mock-require');

chai.use(require('chai-http'));

var expect = chai.expect;

var route = '/apitest/shipmentDispatched';

var mockreq = null;

var winstoncls = {
    stream: {
        write: (msg) => { console.log(msg); }
    }
}

const emptycls = { name: 'Dummy class' };

mock('../controllers/ecourier.controller', {
    updateDispatch: function(res,req,config) {
        res.json({ status: 'OK' });
    }
});

mock.reRequire('../controllers/ecourier.controller');

import routes from '../routes';

server.use('/apitest', routes({ emptycls, emptycls, emptycls, winstoncls }));

**Comment by boblauer** [comment]
Instead of `import` routes, trying using `require`.

**Comment by saiait** [comment]
Thanks for the reply, Tried require instead still not picking up the mock,  any other ideas?

import chai from 'chai';
import server from '..';
import { version } from '../../package.json';

var mock = require('mock-require');

chai.use(require('chai-http'));

var expect = chai.expect;

var route = '/apitest/shipmentDispatched';

var mockreq = null;

var winstoncls = {
    stream: {
        write: (msg) => { console.log(msg); }
    }
}

const emptycls = { name: 'Dummy class' };

mock('../controllers/ecourier.controller', {
    updateDispatch: function(res,req,config) {
        res.json({ status: 'OK' });
    }
});

mock.reRequire('../controllers/ecourier.controller');

var rtes = require('../routes').default;

server.use('/apitest', rtes({ emptycls, emptycls, emptycls, winstoncls }));

describe('Base API route path', () => {

**Comment by boblauer** [comment]
It's really hard to say without seeing the full code.

One thing you could try is setup your mock in a separate file before anything else gets required. In mocha that's `mocha -r setup-mocks.js .`

**Comment by saiait** [comment]
That worked, Thank you so much, appreciate the help.
