### ISSUE TITLE
Does this also work with Es2015 ?

### ISSUE THREAD

**Issue by scaljeri** [boblauer/mock-require#6]
I'm trying to use this library, but so far it doesn't seem to work.

I've created a test [repo](https://github.com/scaljeri/mock-require) for this
If you run the code, the original function is still executed.

Any help would be appreciated!

**Comment by boblauer** [comment]
Looks like it won't work.  Here's the original code:

```js
import mock from 'mock-require';

mock('./foo', () => {
    return 10;
});

import bar from './bar';

console.log(bar());
```

and here's the transpiled code from babel:

```javascript
'use strict';

var _mockRequire = require('mock-require');

var _mockRequire2 = _interopRequireDefault(_mockRequire);

var _bar = require('./bar');

var _bar2 = _interopRequireDefault(_bar);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

(0, _mockRequire2.default)('./foo', function () {
    return 10;
});

console.log((0, _bar2.default)());
```

You can see above that the `import` statements are moved to the top of the file, and so `require('./bar')` executes before `mock('./foo', ...)`.  

Sadly, I don't see a way around this.  That's a bummer.

**Comment by scaljeri** [comment]
Thats too bad. Do you have any suggestions for a good alternative ?

**Comment by boblauer** [comment]
https://github.com/thlorenz/proxyquire is worth checking out

**Comment by scaljeri** [comment]
thnx a lot!

**Comment by tom-s** [comment]
Hi there,

In case anybody is interested, it does work if you include it in a bootstrap file
In my package json, I require a bootstrap file

"test": "node_modules/.bin/mocha  --require app/tests/mocha/bootstrap.js --compilers js:babel-core/register app/tests/mocha/**/*Spec.js --recursive",

My bootstrap file then contains (the config/conf being my webpack alias) : 
// Mock webpack aliases
import mock from 'mock-require'
mock('config/conf', '../../config/conf')

Works like a charm !

**Comment by jtremback** [comment]
The only reason that this doesn't work is that import statements are hoisted. If you simply use an old-fashioned require for the things you need to mock out, it will work fine.
