### ISSUE TITLE
Very good!

### ISSUE THREAD

**Issue by tamtakoe** [boblauer/mock-require#7]
This is one module which can mock React modules, resolve paths, don't launch original dependencies, etc. Thanks!

**Comment by boblauer** [comment]
Thanks, I appreciate that!

**Comment by ianstormtaylor** [comment]
Just wanted to second that @boblauer. I just tried a bunch of the "more popular" mocking libraries and nothing was working, only to find this really simple solution that works perfectly. Thank you!

**Comment by boblauer** [comment]
Thank you for the kind words, I appreciate it.
