### ISSUE TITLE
How to use mock-require with execa?

### ISSUE THREAD

**Issue by moroshko** [boblauer/mock-require#9]
First of all, thanks for a great module!

I'm trying to use `mock-require` with [`execa`](https://github.com/sindresorhus/execa), but unfortunately the mock doesn't run.

Here is the gist of my test:

```js
const mock = require('mock-require');
const execa = require('execa');

mock('analyze-deps', './analyze-deps-mock');

it('should ...', () => {
  return expect(execa('./bin/deps'))
    .to.eventually.have.property('stdout').equal('something');
});
```

where `./bin/deps` is simply:
```js
#!/usr/bin/env node

require('../index');
```

With this setup, `./analyze-deps-mock` is not run.

If I replace `execa('./bin/deps')` with `require('../index')`, then `./analyze-deps-mock` is run as expected.

I assume the problem is that `execa` spawns a new process, but not sure how to workaround this.

Any ideas?

---

**To reproduce:**

1.  `git clone git@github.com:moroshko/analyze-deps-cli.git`
2. `cd analyze-deps-cli`
3. `git checkout 93251ff`
4. `npm install`
5. `npm test`

**Comment by boblauer** [comment]
Thanks for the easy reproduction steps, makes this so much easier to help you with.

Your assumption about `execa` spawning a new process being the problem is correct.  I was able to get this working by moving the mocking of `analyze-deps` to the top of `./bin/deps`, so that it mocks the `require` statement inside of the new process.

```js
#!/usr/bin/env node
const mock = require('mock-require');
mock('analyze-deps', '../test/analyze-deps-mock');

require('../index');
```

**Comment by moroshko** [comment]
Thanks @boblauer!

[I actually ended up doing exactly what you suggest.](https://github.com/moroshko/analyze-deps-cli/blob/f9a9cca212666925a207b323017bd42cf5faa3f7/test/bin/deps)

The main problem with this approach is that I have to create `test/bin/deps` for testing, which could potentially diverge from the real `bin/deps` which is shipped to npm.

I was wondering if you have any ideas how to extend `mock-require` for this use case. But, if this is something that you consider out of scope for this library, I will understand, and happy to close this issue.

Thanks for your quick reply anyway!

**Comment by boblauer** [comment]
What if `test/bin/deps` looks like this?

```js
#!/usr/bin/env node
const mock = require('mock-require');
mock('analyze-deps', '../analyze-deps-mock');

require('../bin/deps');
```

That way all it does is set up the mock require and then execute the real bin/deps, meaning it can't get out of sync from the real bin/deps.

There is no change I can make to the code to allow mocking the require statement across processes, so hopefully my suggestion will work or we can come up with something else that works.

**Comment by moroshko** [comment]
Yeah, it works 😄 
Let's close this issue for now.
Thanks a lot for your help!
